install: skip

env:
  global:
    - GRAVIS_REPO="https://github.com/DanySK/Gravis-CI.git"
    - GRAVIS="$HOME/gravis"
  matrix:
    - JDK="adopt@1.8.0-252"

branches:
  only:
    - master

jobs:
  include:
    - stage: test
      name: "Windows"
      os: windows
      language: shell
      before_install:
        - travis_retry git clone --depth 1 $GRAVIS_REPO $GRAVIS
        - source $GRAVIS/install-jdk
        - java -version
      before_script: "./gradlew -Prelease.version=0.0.0-SNAPSHOT clean publishPluginsToMavenLocal publishMetadataPublicationToMavenLocal publishKotlinMultiplatformPublicationToMavenLocal publishMingwX64PublicationToMavenLocal"
      script:
        - "./gradlew mingwX64Test"
        - "cd demo-project"
        - "./gradlew clean mingwX64Test"

    - stage: test
      name: "MacOS & iOS"
      os: osx
      osx_image: xcode11
      language: java
      before_script: "./gradlew -Prelease.version=0.0.0-SNAPSHOT clean publishPluginsToMavenLocal publishMetadataPublicationToMavenLocal publishKotlinMultiplatformPublicationToMavenLocal publishMacosX64PublicationToMavenLocal publishIosX64PublicationToMavenLocal publishIosArm64PublicationToMavenLocal"
      script:
        - "./gradlew macosX64Test iosX64Test"
        - "cd demo-project"
        - "./gradlew clean macosX64Test iosX64Test"

    - stage: test
      name: "Linux"
      os: linux
      language: java
      before_script: "./gradlew -Prelease.version=0.0.0-SNAPSHOT clean publishPluginsToMavenLocal publishMetadataPublicationToMavenLocal publishKotlinMultiplatformPublicationToMavenLocal publishLinuxX64PublicationToMavenLocal"
      script:
        - "./gradlew linuxX64Test"
        - "cd demo-project"
        - "./gradlew clean linuxX64Test"

    - stage: test
      name: "JavaScript"
      language: java
      before_script: "./gradlew -Prelease.version=0.0.0-SNAPSHOT clean publishPluginsToMavenLocal publishMetadataPublicationToMavenLocal publishKotlinMultiplatformPublicationToMavenLocal publishLinuxX64PublicationToMavenLocal publishJsPublicationToMavenLocal"
      script:
        - "./gradlew jsTest jsNodeTest"
        - "cd demo-project"
        - "./gradlew clean jsTest jsNodeTest"

    - stage: test
      name: "JVM"
      language: java
      before_script: "./gradlew -Prelease.version=0.0.0-SNAPSHOT clean publishPluginsToMavenLocal publishMetadataPublicationToMavenLocal publishKotlinMultiplatformPublicationToMavenLocal publishLinuxX64PublicationToMavenLocal publishJvmPublicationToMavenLocal"
      script:
        - "./gradlew jvmTest"
        - "cd demo-project"
        - "./gradlew clean jvmTest"

    - stage: test
      name: "Android"
      language: android
      dist: trusty
      android:
        components:
          - build-tools-29.0.2
          - android-29
      before_script: "./gradlew -Prelease.version=0.0.0-SNAPSHOT clean publishPluginsToMavenLocal publishMetadataPublicationToMavenLocal publishKotlinMultiplatformPublicationToMavenLocal publishLinuxX64PublicationToMavenLocal publishJvmPublicationToMavenLocal publishAndroidDebugPublicationToMavenLocal publishAndroidReleasePublicationToMavenLocal"
      script:
        - "./gradlew testDebugUnitTest"
        - "cd demo-project"
        - "./gradlew clean compileKotlinLinuxX64 testDebugUnitTest"