name: release

on:
  workflow_dispatch:
    inputs:
      scope:
        description: 'Scope of release. Use major|minor|patch'
        required: true

jobs:
  "Linux":
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Release
        run: ./gradlew final publish -Prelease.scope=${{ github.event.inputs.scope }} -PisMainHost=true -Dorg.ajoberstar.grgit.auth.username=Virelion -Dorg.ajoberstar.grgit.auth.password=${{ secrets.GITHUB_TOKEN }}

  "MacOS-and-iOS":
    name: MacOS & iOS
    needs: [ Linux ]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Release
        run: ./gradlew final :buildata-runtime:publish -Prelease.useLastTag=true -Dorg.ajoberstar.grgit.auth.username=Virelion -Dorg.ajoberstar.grgit.auth.password=${{ secrets.GITHUB_TOKEN }}

  "Windows":
    runs-on: windows-2019
    needs: [ Linux ]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Release
        shell: cmd
        run: .\gradlew.bat final :buildata-runtime:publish -Pkotlin.native.linux.enabled=false -Prelease.useLastTag=true -Dorg.ajoberstar.grgit.auth.username=Virelion -Dorg.ajoberstar.grgit.auth.password=${{ secrets.GITHUB_TOKEN }}
