name: release

on:
  workflow_dispatch:
    inputs:
      scope:
        description: 'Scope of release. Use major|minor|patch'
        required: true

jobs:
  "Initialize-Staging":
    runs-on: ubuntu-latest
    outputs:
      stagingRepositoryId: ${{ steps.init.outputs.stagingRepositoryId }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'
          java-package: 'jdk'
      - name: Create Git Tag and Initialize Staging Repo
        id: init
        run: |
          ./gradlew final initializeSonatypeStagingRepository \
            -Prelease.scope=${{ github.event.inputs.scope }} \
            -Psonatype.username=${{ secrets.SONATYPE_USER_NAME }} \
            -Psonatype.password=${{ secrets.SONATYPE_PASSWORD }}
          
          REPO_ID=$(grep -oP 'Created staging repository \K[^\s]+' build/nexus-staging-plugin/sonatype.properties || echo "")
          echo "stagingRepositoryId=$REPO_ID" >> $GITHUB_OUTPUT

  "Linux":
    needs: [ Initialize-Staging ]
    runs-on: ubuntu-latest
    env:
      GPG_SECRET_KEY: ${{ secrets.GPG_SECRET_KEY }}
      GPG_SECRET_PASSWORD: ${{ secrets.GPG_SECRET_PASSWORD }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'
          java-package: 'jdk'
      - name: Release Linux Artifacts
        run: >
          ./gradlew publishToSonatype
          -PisMainHost=true
          -Prelease.useLastTag=true
          -Psonatype.stagingRepositoryId=${{ needs['Initialize-Staging'].outputs.stagingRepositoryId }}
          -Psonatype.password=${{ secrets.SONATYPE_PASSWORD }}
          -Psonatype.username=${{ secrets.SONATYPE_USER_NAME }}

  "MacOS-and-iOS":
    needs: [ Initialize-Staging ]
    runs-on: macos-latest
    env:
      GPG_SECRET_KEY: ${{ secrets.GPG_SECRET_KEY }}
      GPG_SECRET_PASSWORD: ${{ secrets.GPG_SECRET_PASSWORD }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'
          java-package: 'jdk'
      - name: Release MacOS & iOS Artifacts
        run: >
          ./gradlew :buildata-runtime:publishToSonatype
          -Pkotlin.native.linux.enabled=false
          -Prelease.useLastTag=true
          -Psonatype.stagingRepositoryId=${{ needs['Initialize-Staging'].outputs.stagingRepositoryId }}
          -Psonatype.password=${{ secrets.SONATYPE_PASSWORD }}
          -Psonatype.username=${{ secrets.SONATYPE_USER_NAME }}

  "Windows":
    needs: [ Initialize-Staging ]
    runs-on: windows-latest
    env:
      GPG_SECRET_KEY: ${{ secrets.GPG_SECRET_KEY }}
      GPG_SECRET_PASSWORD: ${{ secrets.GPG_SECRET_PASSWORD }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'
          java-package: 'jdk'
      - name: Release Windows Artifacts
        shell: cmd
        run: >
          .\gradlew.bat :buildata-runtime:publishToSonatype
          -Pkotlin.native.linux.enabled=false
          -Prelease.useLastTag=true
          -Psonatype.stagingRepositoryId=${{ needs['Initialize-Staging'].outputs.stagingRepositoryId }}
          -Psonatype.password=${{ secrets.SONATYPE_PASSWORD }}
          -Psonatype.username=${{ secrets.SONATYPE_USER_NAME }}

  "Close-Staging":
    needs: [ Initialize-Staging, Linux, MacOS-and-iOS, Windows ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'
          java-package: 'jdk'
      - name: Close and Release Staging Repository
        run: >
          ./gradlew closeAndReleaseSonatypeStagingRepository
          -Prelease.useLastTag=true
          -Psonatype.stagingRepositoryId=${{ needs['Initialize-Staging'].outputs.stagingRepositoryId }}
          -Psonatype.password=${{ secrets.SONATYPE_PASSWORD }}
          -Psonatype.username=${{ secrets.SONATYPE_USER_NAME }}