name: release

on:
  workflow_dispatch:
    inputs:
      scope:
        description: 'Scope of release. Use major|minor|patch'
        required: true

jobs:
  "Linux":
    runs-on: ubuntu-latest
    env:
      GPG_SECRET_KEY: ${{ secrets.GPG_SECRET_KEY }}
      GPG_SECRET_PASSWORD: ${{ secrets.GPG_SECRET_PASSWORD }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'
          java-package: 'jdk'
      - name: Release
        run: >
          ./gradlew final publish
          -Prelease.scope=${{ github.event.inputs.scope }}
          -PisMainHost=true
          -Psonatype.token=${{ secrets.SONATYPE_PASSWORD }}
          -Psonatype.username=${{ secrets.SONATYPE_USER_NAME }}

  "MacOS-and-iOS":
    name: MacOS & iOS
    needs: [ Linux ]
    runs-on: macos-latest
    env:
      GPG_SECRET_KEY: ${{ secrets.GPG_SECRET_KEY }}
      GPG_SECRET_PASSWORD: ${{ secrets.GPG_SECRET_PASSWORD }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'
          java-package: 'jdk'
      - name: Release
        run: >
          ./gradlew final :buildata-runtime:publish
          -Pkotlin.native.linux.enabled=false
          -Prelease.useLastTag=true
          -Psonatype.token=${{ secrets.SONATYPE_PASSWORD }}
          -Psonatype.username=${{ secrets.SONATYPE_USER_NAME }}

  "Windows":
    runs-on: windows-latest
    needs: [ Linux ]
    env:
      GPG_SECRET_KEY: ${{ secrets.GPG_SECRET_KEY }}
      GPG_SECRET_PASSWORD: ${{ secrets.GPG_SECRET_PASSWORD }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'
          java-package: 'jdk'
      - name: Release
        shell: cmd
        run: >
          .\gradlew.bat final :buildata-runtime:publish
          -Pkotlin.native.linux.enabled=false
          -Prelease.useLastTag=true
          -Psonatype.token=${{ secrets.SONATYPE_PASSWORD }}
          -Psonatype.username=${{ secrets.SONATYPE_USER_NAME }}