name: release

on:
  workflow_dispatch:
    inputs:
      scope:
        description: 'Scope of release. Use major|minor|patch'
        required: true

jobs:
  "Linux":
    runs-on: ubuntu-latest
    env:
      GPG_SECRET_KEY: ${{ secrets.GPG_SECRET_KEY }}
      GPG_SECRET_PASSWORD: ${{ secrets.GPG_SECRET_PASSWORD }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
          java-package: 'jdk'
      - name: Release
        run: >
          ./gradlew final publish
          -PisReleasingWithSigning=true
          -Prelease.scope=${{ github.event.inputs.scope }}
          -PisMainHost=true
          -Dorg.ajoberstar.grgit.auth.username=Virelion
          -Dorg.ajoberstar.grgit.auth.password=${{ secrets.GITHUB_TOKEN }}
          -Pnexus.token=${{ secrets.NEXUS_TOKEN }}
          -Pnexus.username=${{ secrets.NEXUS_USERNAME }}

  "GradlePlugin":
    name: Gradle Plugin
    needs: [ Linux ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
          java-package: 'jdk'
      - name: Release
        run: >
          ./gradlew final publishPlugins
          -Pkotlin.native.linux.enabled=false
          -Prelease.useLastTag=true
          -Pgradle.publish.key=${{ secrets.GRADLE_PUBLISH_KEY }}
          -Pgradle.publish.secret=${{ secrets.GRADLE_PUBLISH_SECRET }}

  "MacOS-and-iOS":
    name: MacOS & iOS
    needs: [ Linux ]
    runs-on: macos-latest
    env:
      GPG_SECRET_KEY: ${{ secrets.GPG_SECRET_KEY }}
      GPG_SECRET_PASSWORD: ${{ secrets.GPG_SECRET_PASSWORD }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
          java-package: 'jdk'
      - name: Release
        run: >
          ./gradlew final :buildata-runtime:publish
          -PisReleasingWithSigning=true
          -Pkotlin.native.linux.enabled=false
          -Prelease.useLastTag=true
          -Pnexus.token=${{ secrets.NEXUS_TOKEN }}
          -Pnexus.username=${{ secrets.NEXUS_USERNAME }}

  "Windows":
    runs-on: windows-latest
    needs: [ Linux ]
    env:
      GPG_SECRET_KEY: ${{ secrets.GPG_SECRET_KEY }}
      GPG_SECRET_PASSWORD: ${{ secrets.GPG_SECRET_PASSWORD }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
          java-package: 'jdk'
      - name: Release
        shell: cmd
        run: >
          .\gradlew.bat final :buildata-runtime:publish
          -PisReleasingWithSigning=true
          -Pkotlin.native.linux.enabled=false
          -Prelease.useLastTag=true
          -Pnexus.token=${{ secrets.NEXUS_TOKEN }}
          -Pnexus.username=${{ secrets.NEXUS_USERNAME }}