name: verification

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  "MacOS-and-iOS":
    name: MacOS & iOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Unit tests
        run: >
          ./gradlew
          -PisMainHost=true
          -Prelease.version=0.0.0-SNAPSHOT
          clean publishPluginsToMavenLocal
          publishMetadataPublicationToMavenLocal
          publishKotlinMultiplatformPublicationToMavenLocal
          publishMacosX64PublicationToMavenLocal
          publishIosX64PublicationToMavenLocal
          publishIosArm64PublicationToMavenLocal
          macosX64Test iosX64Test
      - name: Integration tests
        working-directory: integration-test-project
        run: ./gradlew clean macosX64Test iosX64Test

  "Linux":
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Unit tests
        run: >
          ./gradlew ktlintCheck
          -PisMainHost=true
          -Prelease.version=0.0.0-SNAPSHOT
          clean publishPluginsToMavenLocal
          publishMetadataPublicationToMavenLocal
          publishKotlinMultiplatformPublicationToMavenLocal
          publishLinuxX64PublicationToMavenLocal
          linuxX64Test
      - name: Integration tests
        working-directory: integration-test-project
        run: ./gradlew clean ktlintCheck linuxX64Test

  "Windows":
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - name: Unit tests
        shell: cmd
        run: >
          .\gradlew.bat
          -PisMainHost=true
          -Prelease.version=0.0.0-SNAPSHOT
          clean publishPluginsToMavenLocal
          publishMetadataPublicationToMavenLocal
          publishKotlinMultiplatformPublicationToMavenLocal
          publishMingwX64PublicationToMavenLocal
          mingwX64Test
      - name: Integration tests
        working-directory: integration-test-project
        run: .\gradlew.bat clean mingwX64Test

  "JavaScript":
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Unit tests
        run: >
          ./gradlew
          -PisMainHost=true
          -Prelease.version=0.0.0-SNAPSHOT
          clean publishPluginsToMavenLocal
          publishMetadataPublicationToMavenLocal
          publishKotlinMultiplatformPublicationToMavenLocal
          publishLinuxX64PublicationToMavenLocal
          publishJsPublicationToMavenLocal
          jsTest jsNodeTest
      - name: Integration tests
        working-directory: integration-test-project
        run: ./gradlew clean jsTest jsNodeTest

  "JVM":
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Unit tests
        run: >
          ./gradlew -PisMainHost=true
          -Prelease.version=0.0.0-SNAPSHOT
          clean publishPluginsToMavenLocal
          publishMetadataPublicationToMavenLocal
          publishKotlinMultiplatformPublicationToMavenLocal
          publishLinuxX64PublicationToMavenLocal
          publishJvmPublicationToMavenLocal
          jvmTest
      - name: Integration tests
        working-directory: integration-test-project
        run: ./gradlew clean jvmTest project-types:jvm:test

  "Android":
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Unit tests
        run: >
          ./gradlew -PisMainHost=true -Prelease.version=0.0.0-SNAPSHOT
          clean publishPluginsToMavenLocal
          publishMetadataPublicationToMavenLocal
          publishKotlinMultiplatformPublicationToMavenLocal
          publishAndroidDebugPublicationToMavenLocal
          publishAndroidReleasePublicationToMavenLocal
          testDebugUnitTest
      - name: Integration tests
        working-directory: integration-test-project
        run: ./gradlew clean testDebugUnitTest

