name: verification

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  "MacOS-and-iOS":
    name: MacOS & iOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v5
        with:
          distribution: 'corretto'
          java-version: '17'
          java-package: 'jdk'
      - name: Unit tests
        run: >
          ./gradlew macosX64Test iosX64Test

  "Linux":
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v5
        with:
          distribution: 'corretto'
          java-version: '17'
          java-package: 'jdk'
      - name: Unit tests
        run: >
          ./gradlew ktlintCheck linuxX64Test  -PisMainHost=true 

  "Windows":
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v5
        with:
          distribution: 'corretto'
          java-version: '17'
          java-package: 'jdk'
      - name: Unit tests
        shell: cmd
        run: >
          .\gradlew.bat mingwX64Test

  "JavaScript":
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v5
        with:
          distribution: 'corretto'
          java-version: '17'
          java-package: 'jdk'
      - name: Unit tests
        run: >
          ./gradlew jsTest jsNodeTest

  "JVM":
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v5
        with:
          distribution: 'corretto'
          java-version: '17'
          java-package: 'jdk'
      - name: Unit tests
        run: >
          ./gradlew jvmTest

  "Android":
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v5
        with:
          distribution: 'corretto'
          java-version: '17'
          java-package: 'jdk'
      - name: Unit tests
        run: >
          ./gradlew testDebugUnitTest

